version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++ build-essential git'
      - run:
          name: Install CMAKE 
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Installing other dependencies
          command: 'apt-get update && apt-get install -y libmariadb-dev libssl-dev zlib1g-dev libasio-dev libwebsocketpp-dev'
      - run:
          name: Cloning aegis
          command: 'git clone https://github.com/zeroxs/aegis.cpp'
      - run:
          name: Building aegis deps
          command: './aegis.cpp/install-deps.sh'
      - run:
          name: Creating aegis build files
          command: 'cmake  -Haegis.cpp -Baegis.cpp/build'
      - run:
          name: Building aegis
          command: 'cmake --build aegis.cpp/build'
      - run:
          name: Installing aegis
          command: 'cmake --install aegis.cpp/build'
      -run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'

