version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++ build-essential git'
      - run:
          name: Install CMAKE 
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Installing other dependencies
          command: 'apt-get update && apt-get install -y libssl-dev zlib1g-dev curl'
      - run:
          name: Installing mysql
          command: 'export DEBIAN_FRONTEND=noninteractive && curl -sSL https://s3.amazonaws.com/circle-downloads/install-mysql5.7-circleci.sh | sh'
      - run:
          name: Cloning aegis
          command: 'git clone https://github.com/zeroxs/aegis.cpp'
      - run:
          name: Checking out and building aegis deps
          command: 'cd aegis.cpp && git submodule init lib/asio && git submodule init lib/json && git submodule init lib/spdlog &&  git submodule init lib/websocketpp && git submodule update && ./install-deps.sh'
      - run:
          name: Creating aegis build files
          command: 'cmake  -Haegis.cpp -Baegis.cpp/build'
      - run:
          name: Building aegis
          command: 'cmake --build aegis.cpp/build'
      - run:
          name: Installing aegis
          command: 'cd aegis.cpp/build && make install'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'

